<?php

/**
 * @file
 * A module...
 */

/**
 * Implements hook_custom_theme().
 *
 * 
 * testing hook_custom_theme().
 */

function bc_theme_switch_custom_theme() {
  return 'news_center';
#  error_log(__LINE__.':'.__FILE__.' $_SERVER = ' . $_SERVER['HTTP_X_DEVICE']);
  if (isset($_SERVER['HTTP_X_DEVICE'])) {
    switch ($_SERVER['HTTP_X_DEVICE']) {
      case 'mobile-tablet':
        // Show the tablet-theme
        return 'dagens';

      case 'mobile-smart':
        // Show the smartphone-theme
        return 'news_center';

      case 'mobile-other':
        // Show our theme for other mobile devices
        return 'news_center';
    }
  }
}
